- name: Wazuh rule deployment
  hosts: managers
  become: true
  vars_files:
    - ../group_vars/secrets/vault.yml
    - ../group_vars/all.yml
  tasks:
    - name: Copy, reload
      #ansible.builtin.include_tasks: ../tasks/wazuh/copy_rules.yml
      ansible.builtin.include_tasks: ../tasks/wazuh/reload_master.yml
