- name: Initialize swarm on first manager
  ansible.builtin.command: "docker swarm init --advertise-addr {{ ansible_host }}"
  register: swarm_init
  run_once: true
  failed_when: swarm_init.rc not in [0,1]   # ignore rc=1 (already in swarm)
  changed_when: swarm_init.rc == 0          # changed only if newly initialized

- name: Retrieve manager join token
  ansible.builtin.command: "docker swarm join-token manager -q"
  register: manager_token
  run_once: true
  failed_when: manager_token.rc != 0
  changed_when: false   # retrieving info, does not change system

- name: Retrieve worker join token
  ansible.builtin.command: "docker swarm join-token worker -q"
  register: worker_token
  run_once: true
  failed_when: worker_token.rc != 0
  changed_when: false   # retrieving info, does not change system

- name: Set manager join command as a fact
  ansible.builtin.set_fact:
    manager_join_command: "docker swarm join --token {{ manager_token.stdout }} {{ ansible_host }}:2377"
    delete_to: workers
    delegate_fact: true

- name: Set worker join command as a fact
  ansible.builtin.set_fact:
    worker_join_command: "docker swarm join --token {{ worker_token.stdout }} {{ ansible_host }}:2377"
    delete_to: workers
    delegate_fact: true
