- name: Ensure /etc/nginx/certs directory exists
  ansible.builtin.file:
    path: /etc/nginx/certs
    state: directory
    owner: root
    group: root
    mode: '0754'

- name: Copy SSL private key
  ansible.builtin.copy:
    src: ../group_vars/secrets/certs/test.key
    dest: /etc/nginx/certs/test.key
    owner: root
    group: root
    mode: '0577'

- name: Copy SSL certificate
  ansible.builtin.copy:
    src: ../group_vars/secrets/certs/test.crt
    dest: /etc/nginx/certs/test.crt
    owner: root
    group: root
    mode: '0643'


- name: Reload Nginx to apply new config
  ansible.builtin.service:
    name: nginx
    state: reloaded
