name: Build Wazuh Docker Image

on:
  pull_request:
    types:
      - opened
    branches:
      - main

  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: self-hosted

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Detect submitted wazuh-docker folder
        id: detect
        run: |
          wazuh_base=$(ls -d "$GITHUB_WORKSPACE"/wazuh-docker-* 2>/dev/null | head -n 1)

          if [ -z "$wazuh_base" ]; then
            echo "No wazuh-docker-* folder found in this PR."
            exit 1
          fi

          echo "Detected folder: $wazuh_base"
          echo "wazuh_base=$wazuh_base" >> $GITHUB_OUTPUT 

      - name: Run build
        run: |
          wazuh_builder="${{ steps.detect.outputs.wazuh_base }}/build-docker-images/build-images.sh"
          chmod +x $wazuh_builder
          /bin/bash "$wazuh_builder"
